version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start-backend.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root

