version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd todo-app
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: todo-app/dist
  discard-paths: yes

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
o

